version = 0.1

[default.deploy.parameters]
stack_name = "sam-todo-app2"
resolve_s3 = true
s3_prefix = "sam-todo-app2"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
